django_todo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from todo.views import ToDoListView, ActiveToDoListView, DoneToDoListView, ToggleDoneView, DeleteToDoView, UpdateToDoView
from django.conf import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'django_todo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', ToDoListView.as_view(), name='home'),
    url(r'^active/$', ActiveToDoListView.as_view(), name='active'),
    url(r'^done/$', DoneToDoListView.as_view(), name='done'),
    url(r'^toggle/(?P<pk>\d+)/$', ToggleDoneView.as_view(), name='toggle'),
    url(r'^delete/(?P<pk>\d+)/$', DeleteToDoView.as_view(), name='delete'),
    url(r'^update/(?P<pk>\d+)/$', UpdateToDoView.as_view(), name='update'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

todo/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models


@python_2_unicode_compatible
class ToDo(models.Model):
    
    description = models.CharField(max_length=255)
    done = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'ToDo'
        verbose_name_plural = "ToDo's"

    def __str__(self):
        return self.description

todo/views.py
from django.views.generic import CreateView, RedirectView, UpdateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.list import MultipleObjectMixin
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse

from .models import ToDo


class ToDoListView(MultipleObjectMixin, CreateView):
    
    model = ToDo
    template_name = 'todo/index.html'
    active_menu = 'all'
    
    success_url = reverse_lazy('home')
    fields = ('description', )
    
    def get_context_data(self, **kwargs):
        self.object_list = self.get_queryset()
        context = super(ToDoListView, self).get_context_data(**kwargs)
        context['todos_left'] = ToDo.objects.filter(done=False).count()
        context['active_menu'] = self.active_menu
        return context
    
    def form_valid(self, form):
        obj = form.save()
        if self.request.is_ajax():
            return HttpResponse(obj.pk)
        return super(ToDoListView, self).form_valid(form)


class ActiveToDoListView(ToDoListView):

    active_menu = 'active'
    
    def get_queryset(self):
        qs = super(ActiveToDoListView, self).get_queryset()
        return qs.filter(done=False)


class DoneToDoListView(ToDoListView):

    active_menu = 'done'
    
    def get_queryset(self):
        qs = super(DoneToDoListView, self).get_queryset()
        return qs.filter(done=True)

class ProcessToDoView(SingleObjectMixin, RedirectView):
    
    model = ToDo
    url = reverse_lazy('home')
    permanent = False
    
    def process(self):
        raise NotImplementedError()
    
    def get(self, request, *args, **kwargs):
        self.process()
        if request.is_ajax():
            return HttpResponse('OK')
        return super(ProcessToDoView, self).get(request, *args, **kwargs)
    

class ToggleDoneView(ProcessToDoView):
    
    def process(self):
        todo = self.get_object()
        todo.done = not todo.done
        todo.save()


class DeleteToDoView(ProcessToDoView):
    
    def process(self):
        todo = self.get_object()
        todo.delete()


class UpdateToDoView(UpdateView):

    model = ToDo
    fields = ('description', )
    
    def form_valid(self, form):
        obj = form.save()
        return HttpResponse('OK')

django_todo/templates/base.html
{% load staticfiles %}


<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django ToDo</title>
    <meta name="description" content="Django ToDo">
    <meta name="author" content="Emma">

    
    <link href="{% static 'css/todo.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.form.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/todo.js' %}"></script>
    

  </head>

  <body>
    
    {% block content %}
    
      <h1 style="text-align: center; margin-top: 50px; color: #666666;">It worked Emma!</h1>
      <h2 style="color: #666666;">Congratulations on your first Django-powered page.</h2>
      <div style="text-align: center; margin-top:75px;">
        <img src="https://raw.githubusercontent.com/pyladies/pyladies-kit/master/pyladies/swag/PyCon%202014/R335555751_A_proof.png"><br/>
        <a href="http://djangopony.com/" class="ponybadge" title="Powered by Django"><img src="http://media.djangopony.com/img/small/badge.png" width="210" height="65" alt="Powered by Django"></a>
      </div>
    
    {% endblock %}
    
  </body>
</html>

todo/templates/todo/index.html
{% extends 'base.html' %}

{% block content %}
  <section class="todoapp">
		<header class="header">
			<h1>ToDo's</h1>
			{% if active_menu == 'all' %}
			  <form method="POST"{% if form.errors %} class="error"{% endif %} id="new">
			    {% csrf_token %}
			    <input class="new-todo ajax" placeholder="What needs to be done?" autofocus name="description"{% if form.description.value %} value="{{form.description.value}}"{% endif %}>
			  </form>
			{% endif %}
		</header>
		<section class="main">
			<ul class="todo-list">
			  {% for todo in todo_list %}
  				<li {% if todo.done %}class="completed"{% endif %}>
  					<div class="view">
  						<input class="toggle ajax" type="checkbox" {%if todo.done %}checked {% endif %}data-target="{% url 'toggle' todo.pk %}">
  						<label>{{ todo.description }}</label>
  						<button class="destroy ajax" data-target="{% url 'delete' todo.pk %}"></button>
  					</div>
  					<form class="edit-form" method="POST" action="{% url 'update' todo.pk %}">
    			    {% csrf_token %}
  					  <input class="edit" name="description" value="{{ todo.description }}">
    			  </form>
  				</li>
  			{% endfor %}
  			<li class="empty-todo">
					<div class="view">
						<input class="toggle ajax" type="checkbox" data-target="{% url 'toggle' 0 %}">
						<label></label>
						<button class="destroy ajax" data-target="{% url 'delete' 0 %}"></button>
					</div>
					<form class="edit-form" method="POST" action="{% url 'update' 0 %}">
  			    {% csrf_token %}
					  <input class="edit" name="description" value="">
  			  </form>
				</li>
			</ul>
		</section>
		<footer class="footer">
			<span class="todo-count"><strong>{{ todos_left }}</strong> item(s) left</span>
			<ul class="filters">
				<li>
					<a href="{% url 'home' %}"{% if active_menu == 'all'%} class="selected"{% endif %}>All</a>
				</li>
				<li>
					<a href="{% url 'active' %}"{% if active_menu == 'active'%} class="selected"{% endif %}>Active</a>
				</li>
				<li>
					<a href="{% url 'done' %}"{% if active_menu == 'done'%} class="selected"{% endif %}>Completed</a>
				</li>
			</ul>
		</footer>
	</section>
{% endblock %}